import libraries

In [1]:
import seaborn as sns 
import pandas as pd
import matplotlib.pyplot as plt
import os

Load iris dataset

In [2]:
#---- if downloaded datset is given then  we can load dataset from pandas like this -----
#data=pd.read_csv("file path")

#seaborn directly create a dataframe in the backend
df=sns.load_dataset('iris')
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

show shape

In [3]:
df.shape

(150, 5)

show column names

In [4]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

show few rows

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Show the structure of the data

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

show the maths statistical summary

In [7]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

Visualize the dataset by using scatter plot that show the relationships between petal_Length and petal_width

In [ ]:
sns.scatterplot(data=df, x="petal_length", y="petal_width", hue="species", palette="Set1")

plt.title("Iris Dataset: Petal Length vs Petal Width")
plt.xlabel("petal_length(cm)")
plt.ylabel("petal_width(cm)")
plt.show()

Scatterpot >>> show the relationship between sepal_length and sepal_width

In [ ]:
sns.scatterplot(data=df, x="sepal_length", y="sepal_width",hue="species",palette="dark")
plt.xlabel("sepal_length(cm)")
plt.ylabel("sepal_width(cm)")
plt.title("Iris Dataset: Sepal Length vs sepal Width")
plt.show()

Histplot of petal length >>> shows that how much flowers is present in the dataset in specific range

In [ ]:
sns.histplot(data=df,x="petal_length")

plt.xlabel("Petal_length(cm)")
plt.ylabel("Numbers Of flowers")
plt.title("Overall Distribution of Petal Lengths in Iris Dataset")
plt.show()

#its shows that k kitny flowers hai jinki length in ranges mai hai pooray dataset mai sai

Histogram of Petal_length of Every Species >>> shows that in every specie how much flower have petal_length is in specific range

In [ ]:
sns.histplot(data=df,x="petal_length",hue="species")

plt.xlabel("Petal_length(cm)")
plt.ylabel("Numbers Of flowers")
plt.title("Species Distribution of Petal Length in Iris Dataset")
plt.show()

#ye mujhy bataraha hai k har species mai kitny flowers hai jinki length in ranges mai hai

Histogram of Petal_width  >>> shows that in all dataset how much flower have petal_width is in specific range

In [ ]:
sns.histplot(data=df,x="petal_width")

plt.xlabel("Petal_length(cm)")
plt.ylabel("Numbers Of flowers")
plt.title("Overall Distribution of Petal Width in Iris Dataset")
plt.show()

#ye mujhy bataraha hai k sarey datset  mai kitny flowers hai jinki width in ranges mai hai

Histogram of Petal_width of Every Species >>> shows that in every specie how much flower have petal_width is in specific range

In [ ]:
sns.histplot(data=df,x="petal_width",hue="species")

plt.xlabel("Petal_length(cm)")
plt.ylabel("Numbers Of flowers")
plt.title("Species Distribution of Petal width in Iris Dataset")
plt.show()

#ye mujhy bataraha hai k har species mai kitny flowers hai jinki width in ranges mai hai

Histogram of sepal_length >>> shows that in all dataset  how much flowers have sepal_length in specific range

In [ ]:
sns.histplot(data=df,x="sepal_length")

plt.xlabel("sepal_length(cm)")
plt.ylabel("Numbers Of flowers")
plt.title("Overall Distribution of sepal_length in Iris Dataset")
plt.show()

#ye mujhy bataraha hai ky pooray datasets mai sai kitny flowers hai jinki sepal_length in ranges mai hai

Histogram of sepal_length of every specie >>> shows that in every specie how much flowers have sepal_length in specific range

In [ ]:
sns.histplot(data=df,x="sepal_length",hue="species")

plt.xlabel("sepal_length(cm)")
plt.ylabel("Numbers Of flowers")
plt.title("Specie Distribution of sepal_length in Iris Dataset")
plt.savefig("graphs/08_Specie_Distribution_of_sepal_length_in_I.png", bbox_inches='tight')
plt.show()

Histogram of sepal_width >>> shows that in all dataset  how much flowers have sepal_width in specific range

In [ ]:
sns.histplot(data=df,x="sepal_width")

plt.xlabel("sepal_width(cm)")
plt.ylabel("Numbers Of flowers")
plt.title("Overall Distribution of sepal_width in Iris Dataset")
plt.show()

Histogram of sepal_width of every specie >>> shows that in every specie how much flowers have sepal_width in specific range

In [ ]:
sns.histplot(data=df,x="sepal_width",hue="species")

plt.xlabel("sepal_width(cm)")
plt.ylabel("Numbers Of flowers")
plt.title("Specie Distribution of sepal_width in Iris Dataset")
plt.show()

BoxPlot of all outlier

In [ ]:
sns.boxplot(data=df, palette="Set2")


plt.title("Box Plot of All Numerical Features in Iris Dataset")
plt.xlabel("all species")
plt.ylabel("lenght in cm")
plt.show()

#after showing graph outliers are detect  only in the sepal width column

Boxplot of petal_length of every specie

In [ ]:
sns.boxplot(data=df, x="species", y="petal_length", palette="Set2")

plt.title("Box Plot of Petal Length for Each Species")
plt.xlabel("Flower Species")
plt.ylabel("Petal Length (cm)")
plt.show()


#In this outliers are detected in the setosa and versicolor in the petal length column

In [ ]:
sns.boxplot(data=df, x="species", y="sepal_length", palette="Set2")

plt.title("Box Plot of sepal Length for Each Species")
plt.xlabel("Flower Species")
plt.ylabel("sepal Length (cm)")
plt.show()


#In this outliers are detected in the virginica in the sepal length column

In [ ]:
sns.boxplot(data=df, x="species", y="petal_width", palette="Set2")

plt.title("Box Plot of Petal width for Each Species")
plt.xlabel("Flower Species")
plt.ylabel("Petal Width (cm)")
plt.show()


#In this outliers are detected only in the setosa  petal width column

In [ ]:
sns.boxplot(data=df, x="species", y="sepal_width", palette="Set2")

plt.title("Box Plot of sepal width for Each Species")
plt.xlabel("Flower Species")
plt.ylabel("Sepal Width (cm)")
plt.show()


#In this outliers are detected o in the setosa and virginica sepal_width column